1. load the numbers csv and convert it to a list

In [1]:
import pandas as pd
df = pd.read_csv("../datasets/numbers.csv")
list_5 = df.values.tolist()
list_5

[[101],
 [102],
 [103],
 [104],
 [105],
 [106],
 [107],
 [108],
 [109],
 [110],
 [111],
 [112],
 [113],
 [114],
 [115],
 [116],
 [117],
 [118],
 [119],
 [120],
 [121],
 [122],
 [123],
 [124],
 [125],
 [126],
 [127],
 [128],
 [129],
 [130],
 [131],
 [132],
 [133],
 [134],
 [135],
 [136],
 [137],
 [138],
 [139],
 [140],
 [141],
 [142],
 [143],
 [144],
 [145],
 [146],
 [147],
 [148]]

2. convert the list to a numpy array

In [2]:
import numpy as np
array_5=np.array(list_5) 

array_5 

array([[101],
       [102],
       [103],
       [104],
       [105],
       [106],
       [107],
       [108],
       [109],
       [110],
       [111],
       [112],
       [113],
       [114],
       [115],
       [116],
       [117],
       [118],
       [119],
       [120],
       [121],
       [122],
       [123],
       [124],
       [125],
       [126],
       [127],
       [128],
       [129],
       [130],
       [131],
       [132],
       [133],
       [134],
       [135],
       [136],
       [137],
       [138],
       [139],
       [140],
       [141],
       [142],
       [143],
       [144],
       [145],
       [146],
       [147],
       [148]])

3. find the sine value of the array

In [3]:
np.sin(array_5) 

array([[ 0.45202579],
       [ 0.99482679],
       [ 0.62298863],
       [-0.3216224 ],
       [-0.97053528],
       [-0.7271425 ],
       [ 0.18478174],
       [ 0.92681851],
       [ 0.81674261],
       [-0.04424268],
       [-0.86455145],
       [-0.8899956 ],
       [-0.09718191],
       [ 0.78498039],
       [ 0.94543533],
       [ 0.23666139],
       [-0.68969794],
       [-0.98195217],
       [-0.3714041 ],
       [ 0.58061118],
       [ 0.99881522],
       [ 0.49871315],
       [-0.45990349],
       [-0.99568699],
       [-0.61604046],
       [ 0.32999083],
       [ 0.97263007],
       [ 0.72103771],
       [-0.19347339],
       [-0.93010595],
       [-0.81160339],
       [ 0.05308359],
       [ 0.86896576],
       [ 0.88592482],
       [ 0.08836869],
       [-0.79043321],
       [-0.94251445],
       [-0.22805226],
       [ 0.69608013],
       [ 0.98023966],
       [ 0.36317137],
       [-0.58779501],
       [-0.99834536],
       [-0.49102159],
       [ 0.46774516],
       [ 0

4. find the log value of the array.

In [4]:
np.log(array_5)

array([[4.61512052],
       [4.62497281],
       [4.63472899],
       [4.6443909 ],
       [4.65396035],
       [4.66343909],
       [4.67282883],
       [4.68213123],
       [4.69134788],
       [4.70048037],
       [4.7095302 ],
       [4.71849887],
       [4.72738782],
       [4.73619845],
       [4.74493213],
       [4.75359019],
       [4.76217393],
       [4.77068462],
       [4.77912349],
       [4.78749174],
       [4.79579055],
       [4.80402104],
       [4.81218436],
       [4.82028157],
       [4.82831374],
       [4.83628191],
       [4.84418709],
       [4.85203026],
       [4.8598124 ],
       [4.86753445],
       [4.87519732],
       [4.88280192],
       [4.89034913],
       [4.8978398 ],
       [4.90527478],
       [4.91265489],
       [4.91998093],
       [4.92725369],
       [4.93447393],
       [4.94164242],
       [4.94875989],
       [4.95582706],
       [4.96284463],
       [4.9698133 ],
       [4.97673374],
       [4.98360662],
       [4.99043259],
       [4.997

5. Find the exponential value of the array 

In [5]:
np.exp(array_5)

array([[7.30705998e+43],
       [1.98626484e+44],
       [5.39922761e+44],
       [1.46766223e+45],
       [3.98951957e+45],
       [1.08446386e+46],
       [2.94787839e+46],
       [8.01316426e+46],
       [2.17820388e+47],
       [5.92097203e+47],
       [1.60948707e+48],
       [4.37503945e+48],
       [1.18925902e+49],
       [3.23274119e+49],
       [8.78750164e+49],
       [2.38869060e+50],
       [6.49313426e+50],
       [1.76501689e+51],
       [4.79781333e+51],
       [1.30418088e+52],
       [3.54513118e+52],
       [9.63666567e+52],
       [2.61951732e+53],
       [7.12058633e+53],
       [1.93557604e+54],
       [5.26144118e+54],
       [1.43020800e+55],
       [3.88770841e+55],
       [1.05678871e+56],
       [2.87264955e+56],
       [7.80867107e+56],
       [2.12261687e+57],
       [5.76987086e+57],
       [1.56841351e+58],
       [4.26338995e+58],
       [1.15890954e+59],
       [3.15024275e+59],
       [8.56324762e+59],
       [2.32773204e+60],
       [6.32743171e+60],
